export default styles = {
    headerAdd:{
        color:'white'
    },

    backGroundView:{
        backgroundColor:'#edeff0',
        flex:1
    },
    inputCard:{
        flexDirection:'column',
        marginHorizontal:15
    },
    inputCardDate:{
        flexDirection:'column',
        marginLeft:15,
        width:'50%'
    },
    textCard:{
        color:"#5f6970",
        marginBottom:10,
        marginTop:20

    },
    viewCard:{
        backgroundColor:'#fbfbfb',
        width:'100%',
        height:50,
        borderRadius:4
    },
    viewCardDes:{
        backgroundColor:'#fbfbfb',
        width:'100%',
        height:120,
        borderRadius:4
    },
    viewPhoteVoice:{
        width:'100%',
        height:'auto',
        position:'absolute',
        bottom:5,
        flexDirection:'row-reverse',
    },
    inputStyle: {
        fontSize: 18,
        lineHeight: 23,
        paddingHorizontal: 20,
    },
    iconButton:{
        marginHorizontal:20
    },
    viewCardDate:{
        backgroundColor:'#fbfbfb',
        width:'100%',
        height:40,
        borderRadius:4,
        alignItems:'center',
       
    },
    dateCard:{
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        justifyContent:'center'
    },
    dateIcon:{
        position:'absolute',
        right:4
    },
    dateView:{
        flexDirection:'row',
        width:'100%'
    },
    buttonPrioritet:{
        height:40,
        alignItems:'center',
        justifyContent:'center',
        width:'50%',
        borderRadius:4,
        backgroundColor:'#bf2e1d'
    },
    buttonPrioritet1:{
        height:40,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'white',
        width:'50%',
        borderRadius:4
    },
    dateText:{
        fontSize:17,
        color:'white'
    },
    dateText1:{
        fontSize:17,
        color:'black'
    }
};